### ISSUE TITLE
Tile images don't have the expected quality

### ISSUE THREAD

**Issue by regiov** [GoogleCloudPlatform/dataflow-zoomify-image#2]
Comparing results with its counterpart tool, ZoomifyFileProcessor.py, which uses the same underlying library for jpeg images (PIL.Image), differences in tile image quality are noticeable. Although this is based on subjective assessment, it's easy to see the differences by zooming in and inspecting the edges. According to documentation, the imageio PIL-JPG driver has a default quality of 75, while ZoomifyFileProcessor.py uses 80. However, even after setting that value to its maximum (100) in dataflow-zoomify-image, quality is still poorer than ZoomifyFileProcessor.py. Why is that?

You can find below an example (check the letters):
1- part of a tile generated with ZoomifyFileProcessor.py
![zoomifyfileprocessor](https://user-images.githubusercontent.com/1180666/137769319-170dc8b5-0acf-485f-93e7-6a2ae2d7bd31.png)
2- same part generated with dataflow-zoomify-image:
![dataflow-zoomify-image](https://user-images.githubusercontent.com/1180666/137769373-e6c955a2-1998-43a4-83f8-133a58d9d7de.png)

**Comment by egonrian** [comment]
I made a commit to use a slower algorithm but with a better perceived quality. Let me know what you think. @regiov

**Comment by regiov** [comment]
@egonrian apparently this one was also solved. I'll now try to merge with our last branch, which I didn't send a pull request as it contains functionality probably too specific for our case (including bigquery to store image metadata and moving the input images to a final bucket after being processed). I just wanted to confirm with you: the new code can handle other file formats, such as png and tiff, but it always saves the corresponding tiles as jpeg, right?

**Comment by egonrian** [comment]
That is right. It always save in RGB format and as a JPEG file.
