### ISSUE TITLE
Rotated images generate tiles with conflicting orientation

### ISSUE THREAD

**Issue by regiov** [GoogleCloudPlatform/dataflow-zoomify-image#3]
Images with non default orientation are producing tiles that don't match when combined together. This test was performed with a jpeg image. According to the imageio documentation for the PIL-JPG driver, the exifrotate parameter can be used to automatically rotate the image based on the exif flag, and its default value is True. So in theory the default parameter should force automatic rotation of the original image, generating tiles following the same orientation, but apparently this is not working.

Example:
![rotation](https://user-images.githubusercontent.com/1180666/137770572-ef2cc9f6-4a23-4313-8c11-6e84423f7c13.png)
:

**Comment by egonrian** [comment]
I made a commit to rotate according  to EXIF. Let me know if it solves the issue. @regiov

**Comment by regiov** [comment]
Problem solved @egonrian. Thanks!
